services:
  ollama:
    image: ollama/ollama:rocm
    ports:
      - 11434:11434
    volumes:
      - ./model_files:/model_files
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - "OLLAMA_KEEP_ALIVE=24h"
      - "OLLAMA_HOST=0.0.0.0"
      - "HSA_OVERRIDE_GFX_VERSION=11.0.0"
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    entrypoint: ["/bin/sh", "/model_files/run_ollama.sh"]
    networks:
      - ollama-docker

volumes:
    ollama:

networks:
  ollama-docker:
    external: false